services:
  jore4-hasura:
    image: "hsldevcom/jore4-hasura:hsl-main--20230418-ef6ce5740b17e02c7c75fd88bd4fb29d59b301f0"
    secrets:
      - source: db-jore3importer-username
        target: /mnt/secrets-store/db-jore3importer-username

secrets:
  db-jore3importer-username:
    file: ./secret-testdb-db-jore3importer-username
