services:
  jore4-hasura:
    image: "hsldevcom/jore4-hasura:main--e04e05996bf41fe7b3e75942f865b1f321e411b9"
    secrets:
      - source: db-jore3importer-username
        target: /mnt/secrets-store/db-jore3importer-username

secrets:
  db-jore3importer-username:
    file: ./secret-testdb-db-jore3importer-username
